### ISSUE TITLE
 esp-idf-hal version

### ISSUE THREAD

**Issue by lonesometraveler** [shanemmattner/esp32c3_rust_tutorials#1]
Hi there,

I wanted to reach out and say that I find this project great. 

I was wondering if there's a reason why you have pinned `esp-idf-hal` to version 0.38. Version 0.39 introduced several breaking changes, and as a result, the examples in this repository are not compatible with newer versions of hal. Most beginners tend to start with the latest version, which is currently 0.40.1. It would be more beneficial if the examples worked with the latest version of hal.

**Comment by shanemmattner** [comment]
Thank you! I really appreciate the feedback.  My goal for this repo is to document my embedded Rust learnings and share with others.  A series of increasingly complex Blinky programs seemed like an accessible path.

To answer your question:  I'm not that good of a Rust programmer yet and the initial tutorials I got working used `0.38` so I stuck with that version for the other examples lol.  I'll get these examples updated to the latest version soon.

**Comment by shanemmattner** [comment]
@lonesometraveler all the examples are updated to version `0.40` for `esp-idf-hal`.  Thank you for pointing out this issue!

I would very much appreciate other feedback you may have on any of the examples or other parts of the project.  I plan to make a few short YouTube videos going through the examples in this repo so I'd like to make them as beginner friendly, logical, and correct as possible.  Please open new tickets for any ideas you have.
