### ISSUE TITLE
Suggestion: make the code more generic and portable

### ISSUE THREAD

**Issue by lonesometraveler** [shanemmattner/esp32c3_rust_tutorials#2]
Great work. Can't wait for YouTube videos. :-)

I understand you're targeting a specific board, but it may be a good idea to make the code more generic and portable so developers with different boards can follow the tutorial without making huge modifications. One way to do this is to use the AnyPin structs, which can help make your code more portable across different microcontrollers.

For example, in the ch-02 program, the LED is tied to a specific pin (`gpio::Gpio8`), which may not be the case on all boards. To make the program more generic, you could use the `AnyOutputPin` struct instead, which allows you to use any output pin that implements the `esp_idf_hal::gpio::OutputPin` trait.

```rust
use esp_idf_hal::{
    gpio::{AnyOutputPin, Output, OutputPin, PinDriver},
    prelude::*,
};
use esp_idf_sys as _;
use std::{thread, time::Duration};

static BLINKY_STACK_SIZE: usize = 2000;

fn main() {
    esp_idf_sys::link_patches();

    let peripherals = Peripherals::take().unwrap();
    let led = PinDriver::output(peripherals.pins.gpio8.downgrade_output()).unwrap();  // <- Gpio8 is downgraded to AnyOutputPin
    // print_type_of(&led); -> You no longer need to print the type name. It is always PinDriver<AnyOutputPin, Output>.

    let _blinky_thread = std::thread::Builder::new()
        .stack_size(BLINKY_STACK_SIZE)
        .spawn(move || blinky_thread(led))
        .unwrap();
}

// this takes AnyOutputPin
fn blinky_thread(mut led: PinDriver<AnyOutputPin, Output>) {
    loop {
        thread::sleep(Duration::from_millis(500));
        println!("LED ON");
        led.set_high().unwrap();
        thread::sleep(Duration::from_millis(500));
        println!("LED OFF");
        led.set_low().unwrap();
    }
}
```

This way, you can even create an additional thread and blink two LEDs at the same time using the same `blinky_thread` function.

```rust 
// ....
let _blinky_thread = std::thread::Builder::new()
    .stack_size(BLINKY_STACK_SIZE)
    .spawn(move || blinky_thread(led))
    .unwrap();

let another_led = PinDriver::output(peripherals.pins.gpio10.downgrade_output()).unwrap();
let _another_blinky_thread = std::thread::Builder::new()
    .stack_size(BLINKY_STACK_SIZE)
    .spawn(move || blinky_thread(another_led))
    .unwrap();
```

The ch-02 program is such a small example. If you don't see much benefits, take a look at the ch-03 program. Suppose `AnyOutputPin` struct is used instead of a specific pin in `fsm.rs`. In that case, I can simply copy and paste the `fsm` module into my project and initialize a `Blinky` with whatever pin I have in the main without needing to modify `fsm.rs`.

**Comment by shanemmattner** [comment]
Thank you @lonesometraveler!  I've been searching for how to do exactly this!  I'll refactor the examples to use generic IO types.

**Comment by shanemmattner** [comment]
Repo is refactored to use generic pin passing.
